name: Full frontend lifecycle workflow

on:
  workflow_dispatch:

jobs:
  Ecr-build-push-wf:
    permissions:
      id-token: write
      contents: read
      
    uses: org-548/reusable/.github/workflows/workflow.yaml@main
    with:
      app_unit: client
      ecr-repo-name: client-repo
      values-file: frontend-values.yaml
    secrets:
      github_pat: ${{ secrets.PA_TOKEN }}

