name: Full frontend lifecycle workflow

on:
  repository_dispatch:
    type:
      - trigger-workflow
  workflow_dispatch:

jobs:
  Using-first-reusable-workflow:
    permissions:
      id-token: write
      contents: read
      
    uses: org-548/reusable/.github/workflows/tf-up.yaml@main
    with:
      app_unit: client
      ecr-repo-name: client-repo
      values-file: frontend-values.yaml
    secrets:
      github_pat: ${{ secrets.PA_TOKEN }}

  Using-second-reusable-workflow:
    needs: Using-first-reusable-workflow
    
    permissions:
      id-token: write
      contents: read
  
    uses: org-548/reusable/.github/workflows/k8s-deploy.yaml@main
    with:
      app_unit: client
    secrets:
      github_pat: ${{ secrets.PA_TOKEN }}
      
